@startuml CodeUnits-Overview
title CodeUnits of BitcoinNode

[BitcoinNode]
note as BitcoinNodeNote
  BitcoinNode is a docker-image for simply running a Bitcoin-node in a docker-container.
end note
BitcoinNode .. BitcoinNodeNote


@enduml